### ISSUE TITLE
[QUESTION] How do you call a script?

### ISSUE THREAD

**Issue by LordNex** [crserran/home-alarm#10]
# Question

I'm wanting to make my lights toggle on and off, or red and blue for colored, when the alarm triggers. I've looked through the documentation but couldn't find anything there. 

I could try and setup a webhook maybe and have the alarm systems try and use that address as an mp3 path. But that would also break the audio. 

Any idea of a way to do this?

## Additional information

- Alert involved: [ eg. media_player ]
- AppDaemon version: [ eg. v4.0.1 ]
- Home Alarm version: [ eg. v2.2.1 ]
- HACS version (if installed from there): [ eg. v0.21.5 ]
- Home Assistant Core version: [ eg. v0.105.4 ]

## AppDaemon app configuration

```yaml

home_alarm:
  module: home_alarm
  class: HomeAlarm
  sensors:
    # - binary_sensor.garage_motion
    - binary_sensor.kitchen_window
    - binary_sensor.back_door
    - binary_sensor.back_door_tamper_sensor
  safe_mode: input_boolean.safe_mode
  activation_delay: 15
  stop_delay: 300
  alerts:
    - id: media_player
      sound: https://mydomain.duckdns.org:8123/local/MainAlarm.mp3 #https://bigsoundbank.com/UPLOAD/mp3/0268.mp3
      volume: 1
      loop_delay: 4
      media_players:
        - media_player.living_room_speaker
        - media_player.master_bedroom_speaker
        - media_player.bathroom_speaker
        - media_player.xxxxx_s_room_speaker
    - id: notifier
      notifiers:
        - notify.mobile_app_wwwww
        - notify.mobile_app_yyyyy_
        - notify.mobile_app_zzzzz
        - notify.mobile_app_xxxxx
        - notify.notify
      title: "ALARM ALERT! {sensor} has triggered!"
      message: "Someone/something triggered your Home Alarm! Better check {sensor} and see whats up!!"

```

## Logs

```text
(optional) Add relevant AppDaemon / Home Assistant logs which could help answering the question.
```

## Additional Context

Add any other context or screenshots about the question here.

**Comment by LordNex** [comment]
Ok I did find the new section on your site about the lights. But again I would like to have the lights flash on and off or cycle between colors. I could do this with a script. I just need a way to trigger the script from the alarm trigger. Sorry, hopefully I'm explaining this right.

**Comment by crserran** [comment]
Hi @LordNex,

Yes Home Alarm has Light support. The default behaviour is to toggle the list of lights you set on your `apps.yaml` each second in RED color and brightness set to the maximum that is 255. You can configure your lights with the following config:

```yaml
...
alerts:
    - id: light
      lights:
        - light.your_light_1
        - light.your_light_2
      rgb_color: [255, 0, 0]
      brightness: 255
...
```

I have notice that I forgot to update the documentation for the two last attributes that are `rgb_color` and `brightness`.  You can set your color just writing your RGB Color in that array following [R, G, B] that is [Red, Green, Blue] for 0 to 255 each one. Moreover, you can set your light brightness from 0 to 255. That 2 attributes are common for the all list of lights.

I hope this helped you,
Best regards,

Cristian.

**Comment by LordNex** [comment]
Perfect. Thank you very much. One question. Can you set a second color for the colored lights to go to. If not this'll work, would like to have the colored ones flash red and blue and then the normal ones just toggle. But switching back and forth from white and off or while and red would do it. 

Right now I am just using a light group that contains every light in the house. Do I need to break that out and separate the colored from the normal into 2 separate groups? Again, thanks for all the help. I have already helped a few people I know set this up. And everyone thinks it's nicely done. 

I'm also currently working on true facial recognition and I'm close. I'm only doing it with cheap Wyze cams and RSTP. Working now to make it easy to train new faces by training with a service that points to a picture file. I've already got DOODS doing basic object recognition and notifications and alarm triggers setup based on that. I have a Wyze lock and keypad coming this week too. Going to see if i can make it check not only facial recognition but GPS and Bluetooth to determine if you are a valid user and then grant access based on that. Would also be cool if I couple figure out a way to pass keypad codes that get entered from the Wyze keypad to be passed to Home Alarm to validate a user. When I get a little closer to that I'll let you know where it leads. 

Peace

**Comment by LordNex** [comment]
Hey would this work for a notification? It works in an automation. Figured I'd ask before I just threw it in and tested it. Thanks

'   - id: notifier
      notifiers:
        - notify.mobile_app_xxxxx
        - notify.notify
      title: "ALARM ALERT! {sensor} has triggered the House Alarm!"
      message: "Someone/something triggered your Home Alarm! Better check {sensor} and see whats up!!"
        data:
        attachment:
        content-type: jpeg
        push:
          category: camera
        entity_id: camera.sidedoorcam `

**Comment by crserran** [comment]
Hi @LordNex 

Sorry for the delay answering. Regarding your first question, by the moment it is not supported to have a second color for a single light alert. If you want to have some lights flashing in RED color an others in BLUE what you can do is create multiple light alerts in the `apps.yaml` file like this:

```yaml
alerts:
    - id: light
      lights:
        - light.your_group_1
      rgb_color: [255, 0, 0]
      brightness: 255
   - id: light
      lights:
        - light.your_group_2
      rgb_color: [0, 0, 255]
      brightness: 255
```

If you have a light that not supports coloring in your group I think that this light just will ignore the color attribute and it will flash normally. Anyway you can test it yourself from Developer tools calling the service light.turn_on and the payload should be similar than this:

```yaml
entity_id: light.your_light_group
rgb_color: [255, 0, 0]
brightness: 255
```

Regarding your last question about notifier, I think that this won't work with Home Alarm but it could be a good improvement.

Your facial recognition systems sounds really nice! If one day you decide to share your system with the community let me know 👍 

Thank you for recommending the system to others.
Regards
