### ISSUE TITLE
LED activation in safe mode does not work...

### ISSUE THREAD

**Issue by Olive80** [crserran/home-alarm#11]
Thank you for this very interesting project.
Everything works fine except the LED which does not light up when the save-mode is activated.
Does the led work with MQTT?
I don't have an esphome / safe-mode topic as described in the configuration ...
Can someone help me please?

**Comment by crserran** [comment]
Hi @Olive80,

Thank you for your question.

For having the `esphome/safe-mode` mqtt topic working I use an automation that publish a message to this topic each time I toggle the `binary_sensor.safe_mode`. 

The automation is the following:
```yaml
alias: Safe Mode publish MQTT state
description: ''
trigger:
  - entity_id: binary_sensor.safe_mode
    platform: state
condition: []
action:
  - data_template:
      payload: |
        {% if is_state("binary_sensor.safe_mode", "off") %}
          OFF
        {% elif is_state("binary_sensor.safe_mode", "on") %}
          ON
        {% endif %}
      topic: esphome/safe_mode
    service: mqtt.publish
mode: single
```

You can try it and let me know if this have solved your problem.
I hope I helped you.
Regards

Cristian.

**Comment by Olive80** [comment]
@crserran
Hi Cristian,
Thank you for your quick reply.
My led still does not work.... 
Is this automation mandatory because I don't see it mentioned anywhere on your website.
I am not an expert with esp32, esphome and arduino cards.
I have an esp32 DevkitC v4 card with the led connected to the gpio 5.
Tell me if you need a screenshot to better understand my problem

**Comment by crserran** [comment]
Hi @Olive80 

Regarding your first question:
> Is this automation mandatory because I don't see it mentioned anywhere on your website.

This automation is needed to publish a message to the MQTT topic in order to wake up all the subscribers. In our case, the subscriber is the ESP32 and then it does the action to turn on/off the LED.

Regarding your ESP32 DevkitC device, if you have used another GPIO for connecting the LED, then you need to modify the `rc522_sensor.h` for using the GPIO 5 in your case.

Line 6 `#define LED_PIN         5        // Configurable`

If you haven't done it previously, you should have this line pointing to PIN 5 and then re-compile the ESP32.

Feel free to send me further information if this solution hasn't solved your issue :)
Regards.

Cristian.

**Comment by Olive80** [comment]
Hi @crserran 
I have already changed my led on the GPIO several times by modifying the rc522.h file but nothing has changed.
My led is not burned out.
I've been trying to solve my problem for several weeks before contacting you, I'm starting to despair ...

I will try to look by the MQTT side.

Question: Is it normal that I have duplicate RFID entities? (esphome and mqtt)
![rfid](https://user-images.githubusercontent.com/58820544/121606616-c9fd1b80-ca4e-11eb-9235-65e13f34f087.PNG)
Is my automation good?
![automatisation_mqtt](https://user-images.githubusercontent.com/58820544/121606792-1ba5a600-ca4f-11eb-842e-6caff9fd2c83.PNG)

Thank for your help

Oliver

**Comment by crserran** [comment]
Hi @Olive80 

Sorry for the delay answering. Your automation seems OK.

Regarding the entities, I have the same entities than you in my config:
<img width="1114" alt="Captura de pantalla 2021-06-15 a las 16 23 32" src="https://user-images.githubusercontent.com/17638335/122070666-73009900-cdf6-11eb-946b-364a29d1af60.png">

I use the `sensor.rfid_id_tiempo_real` entity for configuring an automation that toggles the safe_mode entity like this:
```yaml
alias: Identificación RFID
description: ''
trigger:
  - platform: template
    value_template: >-
      {{ is_state("sensor.rfid_id_tiempo_real", "XXXXXXX") or
      is_state("sensor.rfid_id_tiempo_real", "XXXXXXX") or
      is_state("sensor.rfid_id_tiempo_real", "XXXXXXX") or
      is_state("sensor.rfid_id_tiempo_real", "XXXXXXX") }}
condition: []
action:
  - data: {}
    entity_id: input_boolean.safe_mode
    service: input_boolean.toggle
mode: single
```

For having more information about your issue maybe you can try to modify the `rc522_sensor.h` and set a print on line 46 and 48 which is the method that receives the MQTT message and will be able to see it from the logs. If we see that the message is received correctly then the problem can be on the physical connections probably.

You can also send me the Config Logs in your configuration in order to see if there are Warnings or Error messages.

Regards.

Cristian.
