### ISSUE TITLE
Since update

### ISSUE THREAD

**Issue by titelies** [crserran/home-alarm#4]
@crserran Getting these error messages now since running the HACS update for Home Alarm:
2020-06-10 14:47:56.743479 INFO home_alarm: Welcome to Home Alarm security system.
2020-06-10 14:47:56.748133 WARNING home_alarm: ------------------------------------------------------------
2020-06-10 14:47:56.750332 WARNING home_alarm: Unexpected error in worker for App home_alarm:
2020-06-10 14:47:56.752129 WARNING home_alarm: Worker Ags: {}
2020-06-10 14:47:56.755031 WARNING home_alarm: ------------------------------------------------------------
2020-06-10 14:47:56.757847 WARNING home_alarm: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 143, in initialize_app
    await init()
  File "/config/appdaemon/apps/home-alarm/home_alarm.py", line 22, in initialize
    alert_list = self.parse_alerts(alert_configs)
  File "/config/appdaemon/apps/home-alarm/home_alarm.py", line 79, in parse_alerts
    alert_cls = alerts_dict.get(alert_config["id"])
TypeError: string indices must be integers

Any advice to offer, I'm currently investigating those lines mentioned here...
Wondering if the one issue might be to my configuration of AppDaemon 4 looking like this:
system_packages: []
python_packages: []
init_commands: []
log_level: info

**Comment by crserran** [comment]
Hello @titelies I guess the error could be related to the breaking changes on the new release. Take a look on the new yaml structure, now we have a list of alerts and media players should be inside that list like this:

```yaml
home_alarm:
  module: home_alarm
  class: HomeAlarm
  sensors:
    - binary_sensor.livingroom_window_contact
    - binary_sensor.entrance_door_contact
    - binary_sensor.entrance_motion_occupancy
  safe_mode: input_boolean.safe_mode
  alerts:
    - id: media_player
      sound: amzn_sfx_scifi_alarm_04
      loop_delay: 4
      media_players: 
        - media_player.alexa
        - media_player.alexa2
    - id: notifier
      notifiers:
        - notify.mobile_app_iphone
        - notify.notifier
```

That error you send me looks like the app cannot parse the “id” from the alerts list.

I hope it helps 😊
