### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by rrosson** [crserran/home-alarm#8]
# Question

Currently your documentation states Identification is a work in progress (WiP)

## Additional information

Do you know when this is going to be updated.  What ideas are you throwing around for implementation?

**Comment by crserran** [comment]
Hi @rrosson, I will try to update this section by the end of this week. My idea is to show you the identification system that I am currently using at home with an RFID and an ESP32 and show some images about how are the PINs mapped. Anyway you can use Home Alarm without this identification system due to is a complemented system.

**Comment by LordNex** [comment]
> Hi @rrosson, I will try to update this section by the end of this week. My idea is to show you the identification system that I am currently using at home with an RFID and an ESP32 and show some images about how are the PINs mapped. Anyway you can use Home Alarm without this identification system due to is a complemented system.

Hello, I too just came across your system and am trying to integrate it into my HA as well. I think I understand everything except this part like the guy above. If I or a family member comes home, how would they disarm the system when coming in? Could an audible PIN work or some form of a passcode? Or is this something we would just have to have setup as a switch inside HA and just toggle the entire automation off prior to entry. I guess you could use the device location to automatically disable to automation when they enter the geofence. Anyway kinda just thinking out loud. Would love to get your opinion on what you think a good solution would be. 

Also one other question. I can make another post if you want. I have a house full of Google Home Minis that I plan on using as the speaker system. If I find an mp3 file that I want to play, where to I store it in the HA file structure? Also, do I need to specify the location to the file in the configuration.yaml entry?  Thanks for your hard work!

**Comment by crserran** [comment]
Hi LordNex! Regarding your first question I will say that there are different options. In my case and for the RFID system that I want to show you, each person that are living in your home needs to have their own RFID tag that can be brought in the set-keys and when one arrives at home they just have to approach the RFID tag to the RFID reader. The other approach that you commented is taking into account the location. In that case you won't need the RFID you just need to program automations to active or deactive the secure mode if someone is at home or not. It is also valid and totally supported by Home Alarm.

Regarding your second question, you have to save your local mp3 files into /config/www folder. That is because that folder serves your files via http(s) and Google Home Minis will be able access to your files by the URL like `https://IP:port/local/your_file.mp3`. Your apps.yaml should be like this:

```yaml
home_alarm:
  module: home_alarm
  class: HomeAlarm
  sensors:
    - binary_sensor.entrance_presence_detector
  safe_mode: input_boolean.safe_mode
  activation_delay: 15
  stop_delay: 60
  alerts:
    - id: media_player
      sound: https://YOUR_DNS_NAME/local/alarm.mp3
      volume: 0.8
      media_players:
        - media_player.google_home_1
        - media_player.google_home_2
```

**Comment by xaviml** [comment]
Hi guys,

I would like to have a word in this conversation. I am currently using Home Alarm to control my and my parent's alarm system. I don't have any automation related to the alarm in HA except to activate the safe_mode, which is an input boolean. These are how I toggle the safe_mode in each setup:
- My parent's: I turn on the safe_mode when they leave home and turn it off when they arrive home automatically. They also have the option to toggle the safe_mode from the HA dashboard if needed. The problem is that sometimes they arrive home and the alarm goes off because HA hasn't register they are home yet (or their batteries are flat).
- My own setup: I have an RFID sticker near my door and with the new Tag feature from HA 0.115, I created an automation that toggles the safe_mode every time is scanned. The problem I could have is to run out of battery and not able to disarm the alarm when I arrive home, but it hasn't happened yet. 

Having said this, the preferred setup for me would be the one that @crserran has and described, so having an RFID scanner that toggles the safe_mode when an RFID chip gets scanned in the scanner. [Here](https://github.com/adonno/tagreader) is a nice project that tells you how to set up your own scanner for HA.

Regarding the media player alert, I have it working with 2 Google Home minis and it works like a charm. The only thing to consider is that the GH minis should be able to reproduce media from a HA URL, and this depends on if the router support NAT loopback. In my case it doesn't, so I had to leave HA without SSL and add a reverse proxy with NGINX with the SSL, so I can play a media from my GH minis with a URL like: `http://192.168.X.X:8123/local/alarm.mp3`.

This is my Home Alarm configuration:

```yaml
home_alarm:
  module: home_alarm
  class: HomeAlarm
  sensors:
    - binary_sensor.entrance_presence_detector
  safe_mode: input_boolean.safe_mode
  activation_delay: 15
  stop_delay: 120
  alerts:
    - id: media_player
      sound: http://192.168.X.X:8123/local/alarm.mp3
      loop_delay: 31
      volume: 1
      media_players:
        - media_player.office_speaker
        - media_player.livingroom_speaker
    - id: notifier
      notifiers:
        - notify.mobile_app_xavi_mobile
      title: "ALARM ALERT!"
      message: "Someone/something triggered your alarm!"
```

Regards,
Xavi M.
